# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'

target 'WYNews' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WYNews

pod 'Masonry'
pod 'MJExtension'
pod 'MJRefresh'
pod 'SVProgressHUD'
pod 'AFNetworking'
pod 'YYWebImage'
pod 'FMDB'

end
